language: csharp
mono: none
dotnet: 3.1

install:
 - dotnet restore

script:
 - dotnet build -c Release -p:Version="2.0.$TRAVIS_BUILD_NUMBER"
 - dotnet test

deploy:
  skip_cleanup: true
  provider: script
  script: dotnet nuget push Sekwell/bin/Release/Sekwell.*.nupkg -s "$NUGET_SOURCE" -k "$NUGET_API_KEY"

